function [lambda, distancia_focal, L, M, paso_z, dx, num_granos, ...
    size_grano_del_difusor_x, size_grano_del_difusor_y, R_0, grosor, ...
    amplitud, ang_mayor, ang_menor, FWC50, FWC75, FWC25, tiempo] = archivo_txt(promedio_de_potencia,promedio_de_correlacion,size_grano_del_difusor_x,size_grano_del_difusor_y,...
    filename_5,num_prueba,lambda,distancia_focal,L,M,paso_z,dx,num_granos,...
    R_0,grosor,amplitud,ang_mayor,ang_menor,FWC50,FWC75,FWC25,tiempo)

    % Abrimos el archivo de texto en modo escritura. Este archivo funciona
    % como una bitácora de los parámetros, resultados y tiempo de ejecución
    % correspondientes a la simulación.
    fid = fopen(filename_5,'w');

    %---------------------------------------------------------------
    % Configuración de columnas
    %---------------------------------------------------------------

    % Definimos el ancho de las columnas utilizadas para organizar la
    % información de la simulación en forma de tabla dentro del archivo.
    ancho_simbolo = 12;
    ancho_parametro = 36;
    ancho_valor = 22;
    ancho_unidad = 10;

    % Calculamos el ancho total de la tabla considerando las cuatro columnas
    % y los caracteres empleados como separadores entre ellas.
    ancho_total = ancho_simbolo + ancho_parametro + ...
                  ancho_valor + ancho_unidad + 9;

    %---------------------------------------------------------------
    % Encabezado
    %---------------------------------------------------------------

    % Registramos el número de la simulación y la fecha y hora en que se
    % genera el archivo de bitácora.
    fprintf(fid,'Simulación: %d\n',num_prueba);
    fprintf(fid,'Fecha: %s\n\n',datetime);

    % Generamos la línea superior que delimita el encabezado de la tabla.
    fprintf(fid,'%s\n',repmat('=',1,ancho_total));

    % Escribimos los encabezados de las columnas correspondientes al
    % símbolo, nombre del parámetro, valor y unidad.
    fprintf(fid,'%-*s | %-*s | %-*s | %-*s\n',...
        ancho_simbolo,'Símbolo',...
        ancho_parametro,'Parámetro',...
        ancho_valor,'Valor',...
        ancho_unidad,'Unidad');

    % Separamos el encabezado del conjunto de parámetros de la simulación.
    fprintf(fid,'%s\n',repmat('-',1,ancho_total));

    %---------------------------------------------------------------
    % Parámetros de la simulación
    %---------------------------------------------------------------

    % Registramos la longitud de onda utilizada en la simulación y
    % realizamos la conversión correspondiente a nanómetros.
    fprintf(fid,'%-*s | %-*s | %-*.4f | %-*s\n',...
        ancho_simbolo,'λ',...
        ancho_parametro,'Longitud de onda',...
        ancho_valor,lambda*1e7,...
        ancho_unidad,'nm');
    fprintf(fid,'\n');

    % Registramos la distancia focal de la lente expresada en centímetros.
    fprintf(fid,'%-*s | %-*s | %-*.4f | %-*s\n',...
        ancho_simbolo,'f',...
        ancho_parametro,'Distancia focal',...
        ancho_valor,distancia_focal,...
        ancho_unidad,'cm');
    fprintf(fid,'\n');

    % Registramos el tamaño de la ventana espacial de simulación
    % normalizado respecto al radio central R_0.
    fprintf(fid,'%-*s | %-*s | %-*.4e | %-*s\n',...
        ancho_simbolo,'L',...
        ancho_parametro,'Tamaño de la ventana',...
        ancho_valor,L/lambda,...
        ancho_unidad,'λ');
    fprintf(fid,'\n');

    % Registramos el número total de muestras de la malla bidimensional,
    % expresándolo como una potencia de dos.
    fprintf(fid,'%-*s | %-*s | %-*s | %-*s\n',...
        ancho_simbolo,'M^2',...
        ancho_parametro,'Número de muestras',...
        ancho_valor,sprintf('2^%d',2*log(M)/log(2)),...
        ancho_unidad,'[U.A.]');
    fprintf(fid,'\n');

    % Registramos el paso empleado durante la propagación, normalizado
    % respecto a la distancia focal de la lente.
    fprintf(fid,'%-*s | %-*s | %-*.4e | %-*s\n',...
        ancho_simbolo,'p_z',...
        ancho_parametro,'Paso de propagación',...
        ancho_valor,paso_z/distancia_focal,...
        ancho_unidad,'f');
    fprintf(fid,'\n');

    % Registramos el ancho del intervalo de muestreo espacial, normalizado
    % respecto a la longitud de onda.
    fprintf(fid,'%-*s | %-*s | %-*.4f | %-*s\n',...
        ancho_simbolo,'dx',...
        ancho_parametro,'Ancho del intervalo de muestreo',...
        ancho_valor,dx/lambda,...
        ancho_unidad,'λ');
    fprintf(fid,'\n');

    % Registramos el número de granos utilizados para generar el difusor,
    % normalizado respecto al número de muestras M en una dimensión.
    fprintf(fid,'%-*s | %-*s | %-*s | %-*s\n',...
        ancho_simbolo,'Γ',...
        ancho_parametro,'Número de granos del difusor',...
        ancho_valor,sprintf('%.4f',num_granos/M),...
        ancho_unidad,'M');
    fprintf(fid,'\n');

    %---------------------------------------------------------------
    % Tamaño del grano del difusor
    %---------------------------------------------------------------

    % Calculamos y registramos las dimensiones características de un grano del
    % difusor en las direcciones x e y, normalizadas respecto a la longitud
    % de onda.
    fprintf(fid,'%-*s | %-*s | %-*s | %-*s\n',...
        ancho_simbolo,'α × β',...
        ancho_parametro,'Tamaño del grano del difusor',...
        ancho_valor,sprintf('%.4f × %.4f',...
        size_grano_del_difusor_x/lambda,...
        size_grano_del_difusor_y/lambda),...
        ancho_unidad,'λ^2');
    fprintf(fid,'\n');

    %---------------------------------------------------------------
    % Parámetros ópticos
    %---------------------------------------------------------------

    % Registramos el radio central R_0 del anillo expresado en milímetros.
    fprintf(fid,'%-*s | %-*s | %-*.4e | %-*s\n',...
        ancho_simbolo,'R_0',...
        ancho_parametro,'Radio central',...
        ancho_valor,R_0/lambda,...
        ancho_unidad,'λ');
    fprintf(fid,'\n');

    % Registramos el grosor del anillo normalizado respecto a su radio
    % central R_0.
    fprintf(fid,'%-*s | %-*s | %-*.4f | %-*s\n',...
        ancho_simbolo,'Ω',...
        ancho_parametro,'Grosor',...
        ancho_valor,grosor/lambda,...
        ancho_unidad,'λ');
    fprintf(fid,'\n');

    % Registramos la amplitud asignada al campo óptico inicial.
    fprintf(fid,'%-*s | %-*s | %-*.4f | %-*s\n',...
        ancho_simbolo,'A',...
        ancho_parametro,'Amplitud',...
        ancho_valor,amplitud,...
        ancho_unidad,'[U.A.]');
    fprintf(fid,'\n');

    % Registramos el límite angular superior del campo, expresado en
    % unidades de pi radianes.
    fprintf(fid,'%-*s | %-*s | %-*.4f | %-*s\n',...
        ancho_simbolo,'θ_max',...
        ancho_parametro,'Ángulo mayor',...
        ancho_valor,ang_mayor/pi,...
        ancho_unidad,'π rad');
    fprintf(fid,'\n');

    % Registramos el límite angular inferior del campo, expresado en
    % unidades de pi radianes.
    fprintf(fid,'%-*s | %-*s | %-*.4f | %-*s\n',...
        ancho_simbolo,'θ_min',...
        ancho_parametro,'Ángulo menor',...
        ancho_valor,ang_menor/pi,...
        ancho_unidad,'π rad');
    fprintf(fid,'\n');

    %---------------------------------------------------------------
    % Resultados
    %---------------------------------------------------------------

    % Registramos el ancho completo de la autocorrelación al 50 % de su
    % valor máximo, normalizado respecto al radio R_0.
    fprintf(fid,'%-*s | %-*s | %-*.4e | %-*s\n',...
        ancho_simbolo,'FWC_{0.50}',...
        ancho_parametro,'Ancho de autocorrelación en 0.50',...
        ancho_valor,FWC50/lambda,...
        ancho_unidad,'λ');
    fprintf(fid,'\n');

    % Registramos el ancho completo de la autocorrelación al 75 % de su
    % valor máximo, normalizado respecto al radio R_0.
    fprintf(fid,'%-*s | %-*s | %-*.4e | %-*s\n',...
        ancho_simbolo,'FWC_{0.75}',...
        ancho_parametro,'Ancho de autocorrelación en 0.75',...
        ancho_valor,FWC75/lambda,...
        ancho_unidad,'λ');
    fprintf(fid,'\n');

    % Registramos el ancho completo de la autocorrelación al 25 % de su
    % valor máximo, normalizado respecto al radio R_0.
    fprintf(fid,'%-*s | %-*s | %-*.4e | %-*s\n',...
        ancho_simbolo,'FWC_{0.25}',...
        ancho_parametro,'Ancho de autocorrelación en 0.25',...
        ancho_valor,FWC25/lambda,...
        ancho_unidad,'λ');
    fprintf(fid,'\n');

    % Registramos el valor promedio de la potencia óptica obtenido durante
    % el análisis de la propagación.
    fprintf(fid,'%-*s | %-*s | %-*.4f | %-*s\n',...
        ancho_simbolo,'μ_P',...
        ancho_parametro,'Potencia óptica promedio',...
        ancho_valor,promedio_de_potencia,...
        ancho_unidad,'[U.A.]');
    fprintf(fid,'\n');

    % Registramos el coeficiente de correlación promedio obtenido al
    % comparar las distribuciones de irradiancia durante la propagación
    % con la distribución utilizada como referencia.
    fprintf(fid,'%-*s | %-*s | %-*.4f | %-*s\n',...
        ancho_simbolo,'μ_R',...
        ancho_parametro,'Coeficiente de correlación promedio',...
        ancho_valor,promedio_de_correlacion,...
        ancho_unidad,'[U.A.]');

    %---------------------------------------------------------------
    % Tiempo de ejecución
    %---------------------------------------------------------------

    % Separamos los resultados anteriores del registro correspondiente al
    % tiempo total de ejecución.
    fprintf(fid,'%s\n',repmat('-',1,ancho_total));

    % Registramos el tiempo total de cómputo de la simulación y lo
    % convertimos de segundos a minutos.
    fprintf(fid,'%-*s | %-*s | %-*.4f | %-*s\n',...
        ancho_simbolo,'t',...
        ancho_parametro,'Tiempo de cómputo',...
        ancho_valor,tiempo/60,...
        ancho_unidad,'min');

    % Cerramos visualmente la tabla mediante una línea de separación.
    fprintf(fid,'%s\n',repmat('=',1,ancho_total));

    % Cerramos el archivo de texto una vez registrada toda la información
    % correspondiente a la simulación.
    fclose(fid);

end