function archivo_csv(promedio_de_potencia,promedio_de_correlacion,size_grano_del_difusor_x,size_grano_del_difusor_y,filename_csv,num_prueba,lambda,distancia_focal,L,M,paso_z,dx,num_granos,R_0,grosor,amplitud,ang_mayor,ang_menor,FWC_50,FWC_75,FWC_25,tiempo)

%--------------------------------------------------------------
% Crear tabla con una sola fila
%--------------------------------------------------------------

% Creamos una tabla que funciona como bitácora de la simulación. En
% ella se almacenan los parámetros utilizados, las características
% espaciales del difusor, las métricas obtenidas del análisis de la
% propagación y el tiempo total de ejecución. Algunas magnitudes se
% normalizan o convierten de unidades para facilitar su comparación
% entre diferentes simulaciones.
T = table(...
    num_prueba,...                           % Número identificador de la simulación.
    datetime('now'),...                      % Fecha y hora en que se registra la simulación.
    lambda*1e7,...                           % Longitud de onda expresada en nanómetros.
    distancia_focal,...                      % Distancia focal de la lente expresada en centímetros.
    L/lambda,...                                % Tamaño de la ventana espacial normalizado respecto a R_0.
    M^2,...                                  % Número total de muestras de la malla bidimensional.
    paso_z/distancia_focal,...               % Paso de propagación normalizado respecto a la distancia focal.
    dx/lambda,...                            % Separación entre muestras espaciales normalizada respecto a lambda.
    num_granos/M,...                         % Número de granos del difusor normalizado respecto a M.
    size_grano_del_difusor_x/lambda,...      % Tamaño del grano del difusor en x normalizado respecto a lambda.
    size_grano_del_difusor_y/lambda,...      % Tamaño del grano del difusor en y normalizado respecto a lambda.
    R_0/lambda,...                               % Radio característico R_0 expresado en milímetros.
    grosor/lambda,...                           % Grosor del anillo normalizado respecto a R_0.
    amplitud,...                             % Amplitud asignada al campo óptico inicial.
    ang_mayor/pi,...                         % Límite angular superior expresado en unidades de pi radianes.
    ang_menor/pi,...                         % Límite angular inferior expresado en unidades de pi radianes.
    FWC_50/lambda,...                               % Ancho completo de la autocorrelación al 50 % de su valor máximo, normalizado respecto a R_0.
    FWC_75/lambda,...                               % Ancho completo de la autocorrelación al 75 % de su valor máximo, normalizado respecto a R_0.
    FWC_25/lambda,...                               % Ancho completo de la autocorrelación al 25 % de su valor máximo, normalizado respecto a R_0.
    promedio_de_potencia,...                 % Valor promedio de la potencia durante la propagación.
    promedio_de_correlacion,...              % Coeficiente de correlación promedio durante la propagación.
    tiempo/60,...                            % Tiempo total de ejecución expresado en minutos.
    'VariableNames',{...
    'Prueba',...
    'Fecha',...
    'Lambda_λ',...
    'DistanciaFocal_cm',...
    'Ventana_λ',...
    'Numero_de_muestras',...
    'PasoProp_f',...
    'dx_lambda',...
    'Num_Granos_M',...
    'Tamano_grano_del_difusor_x_λ',...
    'Tamano_grano_del_difusor_y_λ',...
    'Radio_λ',...
    'Grosor_λ',...
    'Amplitud',...
    'Ang_Mayor_[pi rad]',...
    'Ang_Menor_[pi rad]',...
    'FWC50_λ',...
    'FWC75_λ',...
    'FWC25_λ',...
    'P_prom',...
    'R_prom',...
    'Tiempo_min'});

%--------------------------------------------------------------
% Escribir archivo
%--------------------------------------------------------------

% Guardamos la tabla generada en un archivo CSV. De esta manera se
% conserva una bitácora de los parámetros y resultados correspondientes
% a la simulación para su posterior consulta, comparación y análisis.
writetable(T,filename_csv);

end